@echo off
echo Starting Library Reservation System...

echo 1. Launching private MariaDB Server on port 3308...
start "Library MariaDB" /min "C:\Program Files\MariaDB 11.6\bin\mysqld.exe" --defaults-file="%~dp0.db_data\my.ini" --console

echo Waiting for MariaDB to initialize...
timeout /t 3 /nobreak >null

echo 2. Launching Next.js development server on port 3000...
npm run dev
